### ISSUE TITLE
Support large integers

### ISSUE THREAD

**Issue by michaelmior** [fuminori-ido/gurobi#2]
I'm not sure if this is possible because I'm not familiar with the C extension API. However, I noticed that an error is produced if you try to use a `Fixnum` which is not in the range of a C `int`. It would be nice if this could automatically be promoted to a double. (For now I've just resorted to multiplying everything by `1.0` on the Ruby side.)

**Comment by fuminori-ido** [comment]
Thank you for your comment and sorry for my rate reply.

Could you attach the source file which failed against to your expectation.  I'll check what is the better solution.

**Comment by michaelmior** [comment]
No problem. I'll try to put together a simple example soon.

**Comment by michaelmior** [comment]
Sorry for the delay. Here's a simple example which illustrates the problem. The value being multipled in the objective function is a Ruby `Integer`. The code currently tries to represent this as a C `int`, but fails since it's too large with the error

```
test.rb:6:in `*': unknown rhs type (StandardError)
```

If you instead use the float `9999999999999999999.0`, things work as expected.

``` ruby
require 'gurobi'

model = Gurobi::Model.new(Gurobi::Env.new)
var = model.addVar(0, 1, 0, Gurobi::BINARY, "a")
model.update
model.setObjective(var * 9999999999999999999, Gurobi::MAXIMIZE)
model.update
model.optimize
puts var.get_double(Gurobi::DoubleAttr::X)
```

**Comment by fuminori-ido** [comment]
Thank you for your input.  Can I include your code, which is posted above, into our gurobi test code?

**Comment by michaelmior** [comment]
Sure. No problem here :)

**Comment by fuminori-ido** [comment]
I understand that 9999999999999999999 is Bignum value, which is not yet supported in my gurobi wrapper.  C/C++ gurobi API supports only double-type so that Ruby Fixnum and Float are converted to C/C++ double.  I'll write type conversion from Ruby Bignum to Float so that this issue would be solved.

**Comment by michaelmior** [comment]
Thanks! That would be great :)

**Comment by fuminori-ido** [comment]
I commit on 'development' branch and push it to origin(github).

Could you do "git clone", checkout 'development' branch, and see it what you expect?

**Comment by michaelmior** [comment]
Sorry, somehow I didn't see this comment until just now. For some reason it slipped past me. This does seem to work, although I'm curious why you chose to convert to float instead of integer? Using floats is does not seem necessary and reduces the range of values which can be represented. I only used floats in my example on the Ruby side because there's no way to make a Bignum into a Fixnum.

**Comment by michaelmior** [comment]
Actually, now that I think about it, it's probably best to use `NUM2LL` for Bignum and then use a C `long long`.

**Comment by fuminori-ido** [comment]
Thank you for your comment about 'long long'.  However, Gurobi supports only 'double'.  This ruby API just converts between ruby Fixnum, Float, and Bignum <--> C/C++ 'double' so that I think this commit is OK.  I hope you agree...

**Comment by michaelmior** [comment]
Ah, I didn't realize that the Gurobi API only dealt with doubles. If that's the case, then how things work now makes sense.

**Comment by fuminori-ido** [comment]
Thanks for your prompt reply!  Let me close this ticket and release this version as 0.01.00.

**Comment by michaelmior** [comment]
Thanks!
